import json
from typing import TYPE_CHECKING, Any

from litellm import acompletion
from rich.console import Console
from rich.panel import Panel

from src.config import settings
from src.services.mcp_client_manager import McpClientManager
from src.services.plan_auditor import PlanAuditor
from src.utils import logger

if TYPE_CHECKING:
    pass

console = Console()


class AuditOrchestrator:
    """
    Orchestrates the interactive planning loop using Jules Orchestration MCP Tools and PlanAuditor.
    """

    def __init__(
        self,
        mcp_client_manager: McpClientManager,
        sandbox_runner: Any,
        plan_auditor: PlanAuditor | None = None,
    ) -> None:
        self.mcp_client_manager = mcp_client_manager
        if not self.mcp_client_manager:
            msg = "McpClientManager must be injected into AuditOrchestrator"
            raise ValueError(msg)
        self.sandbox = sandbox_runner
        self.auditor = plan_auditor or PlanAuditor()

    async def run_interactive_session( # noqa: C901, PLR0915
        self, prompt: str, spec_files: dict[str, str], max_retries: int = 3
    ) -> dict[str, Any]:
        """
        Starts a session and manages the audit loop via native MCP Orchestration tools.
        """
        console.print(Panel("[bold cyan]Starting AI-on-AI Audit Session (MCP)[/bold cyan]", expand=False))

        file_paths = list(spec_files.keys())

        async with self.mcp_client_manager as mcp_client:
            tools = await mcp_client.get_orchestration_tools("jules")
            if not tools:
                logger.warning("No Jules Orchestration tools found.")
                return {}

            tools_for_llm = []
            tool_map = {}
            for t in tools:
                t_schema = {
                    "type": "function",
                    "function": {
                        "name": t.name,
                        "description": t.description,
                        "parameters": t.args_schema.schema() if t.args_schema else {"type": "object", "properties": {}},
                    }
                }
                tools_for_llm.append(t_schema)
                tool_map[t.name] = t

            retry_count = 0
            feedback_prompt = ""

            while retry_count <= max_retries:
                console.print(f"\n[bold yellow]--- Audit Round {retry_count + 1} ---[/bold yellow]")

                sys_prompt = (
                    "You are the Jules Orchestrator. Use `create_session` to start the process with the given prompt and files.\n"
                    "Since this is an interactive session, ensure you return the plan generated by the session."
                )

                messages = [{"role": "system", "content": sys_prompt}]
                user_msg = f"Task: {prompt}\nFiles: {file_paths}\n"
                if feedback_prompt:
                    user_msg += f"Feedback from last review: {feedback_prompt}"

                messages.append({"role": "user", "content": user_msg})

                response = await acompletion(
                    model=settings.reviewer.smart_model,
                    messages=messages,
                    tools=tools_for_llm,
                    temperature=0.0,
                )

                plan_details = {}
                msg = response.choices[0].message
                if getattr(msg, "tool_calls", None):
                    for tool_call in msg.tool_calls:
                        func_name = tool_call.function.name
                        func_args = json.loads(tool_call.function.arguments)

                        if func_name in tool_map:
                            try:
                                tool = tool_map[func_name]
                                result = await tool.ainvoke(func_args)
                                # Assuming result holds the plan if it's the Orchestrator doing the work
                                plan_details = {"planId": "mcp-plan-1", "content": str(result)}
                            except Exception as e:
                                logger.error(f"Error executing {func_name}: {e}")

                if not plan_details:
                    val_err = "Plan activity found but no details via MCP tools."
                    raise ValueError(val_err)

                audit_result = await self.auditor.audit_plan(
                    plan_details, spec_files, phase="architect"
                )

                style = "green" if audit_result.status == "APPROVED" else "red"
                console.print(
                    Panel(
                        f"Status: {audit_result.status}\nReason: {audit_result.reason}",
                        title="Audit Result",
                        border_style=style,
                    )
                )

                if audit_result.status == "APPROVED":
                    console.print("[bold green]Plan Approved. Proceeding...[/bold green]")
                    return {"status": "success", "plan": plan_details}

                retry_count += 1
                if retry_count > max_retries:
                    run_err = "Max audit retries exceeded."
                    raise RuntimeError(run_err)

                feedback = audit_result.feedback or audit_result.reason
                feedback_prompt = (
                    f"Your plan was REJECTED by the Lead Architect.\n"
                    f"Reason: {audit_result.reason}\n"
                    f"Instruction: {feedback}\n"
                    f"Please revise the plan accordingly."
                )
                console.print(f"[magenta]Generating new plan based on feedback:[/magenta] {feedback}")

        fatal_err = "Session ended unexpectedly."
        raise RuntimeError(fatal_err)
