from typing import Any, Protocol

from src.state import CycleState


class IGraphNodes(Protocol):
    async def architect_session_node(self, state: CycleState) -> dict[str, Any]: ...

    async def architect_critic_node(self, state: CycleState) -> dict[str, Any]: ...

    async def coder_session_node(self, state: CycleState) -> dict[str, Any]: ...

    async def auditor_node(self, state: CycleState) -> dict[str, Any]: ...

    async def committee_manager_node(self, state: CycleState) -> dict[str, Any]: ...

    async def uat_evaluate_node(self, state: CycleState) -> dict[str, Any]: ...

    async def sandbox_evaluate_node(self, state: CycleState) -> dict[str, Any]: ...

    async def global_refactor_node(self, state: CycleState) -> dict[str, Any]: ...

    async def coder_critic_node(self, state: CycleState) -> dict[str, Any]: ...

    def check_coder_outcome(self, state: CycleState) -> str: ...

    def route_architect_critic(self, state: CycleState) -> str: ...

    def route_committee(self, state: CycleState) -> str: ...

    def route_auditor(self, state: CycleState) -> str: ...

    def route_final_critic(self, state: CycleState) -> str: ...

    def route_sandbox_evaluate(self, state: CycleState) -> str: ...

    def route_uat(self, state: CycleState) -> str: ...

    def route_coder_critic(self, state: CycleState) -> str: ...

    async def qa_session_node(self, state: CycleState) -> dict[str, Any]: ...

    async def qa_auditor_node(self, state: CycleState) -> dict[str, Any]: ...

    def route_qa(self, state: CycleState) -> str: ...

    # Define as a variable, not a property, to avoid runtime setter conflicts
    llm_reviewer: Any


class IWorkflowOrchestrator(Protocol):
    async def run_gen_cycles(self, cycles: int, project_session_id: str | None) -> None: ...

    async def run_cycle(
        self,
        cycle_id: str | None,
        resume: bool,
        auto: bool,
        start_iter: int,
        project_session_id: str | None,
        parallel: bool = False,
    ) -> None: ...

    async def start_session(self, prompt: str, audit_mode: bool, max_retries: int) -> None: ...

    async def finalize_session(self, project_session_id: str | None) -> None: ...
