from pydantic import BaseModel, ConfigDict, Field


class SystemArchitecture(BaseModel):
    """
    High-level System Architecture Design.
    Generated by Structurer Agent from raw requirements.
    """

    model_config = ConfigDict(extra="forbid")

    project_name: str = Field(..., description="Name of the project")
    background: str = Field(..., description="Project background and context")
    core_philosophy: str = Field(
        ..., description="Core design philosophy (e.g., minimalist, robust, rapid)"
    )
    user_stories: list[str] = Field(..., description="High-level user stories")
    system_design: str = Field(..., description="Overall system design and architecture pattern")
    module_structure: str = Field(
        ..., description="Breakdown of key modules and responsibilities (hierarchical or list)"
    )
    tech_stack: list[str] = Field(..., description="List of technologies and libraries to be used")
    implementation_roadmap: list[str] = Field(..., description="Step-by-step implementation phases")
