from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class FileArtifact(BaseModel):
    """Generated or modified file artifact"""

    model_config = ConfigDict(extra="forbid")
    path: str = Field(..., description="File path (e.g. dev_documents/CYCLE01/SPEC.md)")
    content: str = Field(..., description="File content")
    language: str = Field("markdown", description="Language (python, markdown, etc.)")


class FileCreate(BaseModel):
    """New file creation"""

    model_config = ConfigDict(extra="forbid")
    operation: Literal["create"] = "create"
    path: str = Field(..., description="Path to the file to create")
    content: str = Field(..., description="Full content of the new file")


class FilePatch(BaseModel):
    """Existing file modification via patch"""

    model_config = ConfigDict(extra="forbid")
    operation: Literal["patch"] = "patch"
    path: str = Field(..., description="Path to the file to modify")
    search_block: str = Field(
        ...,
        description="Exact block of code to search for (must match original file exactly)",
    )
    replace_block: str = Field(
        ..., description="New block of code to replace the search block with"
    )
    git_diff_patch: str | None = Field(
        default=None, description="Unified git diff representing the changes, generated by parallel agents"
    )


FileOperation = FileCreate | FilePatch
